# Welcome to Jekyll!
#

# Site settings
title: Mamang Home
description: |
  Another NPC in this world
owner: Fuad Yusuf P # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: fuadyp@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://terpasang.online" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/fuad_yusuf
  github: https://github.com/parksama
  linkedin-square: https://linkedin.com/in/fuad-yusuf-p-17619878
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/fuad_yusuf/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
